version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  laravel:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www:rw
    depends_on:
      - db
    networks:
      - backend
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./backend:/var/www
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - laravel
    networks:
      - backend

  react:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app:rw
    ports:
      - "3000:3000"
    networks:
      - frontend

networks:
  backend:
  frontend:

volumes:
  db_data:
